[package]
name = "playground"
version = "0.1.0"
authors = ["Adam Chalmers <adam.s.chalmers@gmail.com>"]
edition = "2018"

[dependencies]
tracing = "0.1.25"
tracing-subscriber = { version = "0.2.17", features = ["json"] }
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.64"